<a href="https://colab.research.google.com/github/mohanraju2002/SQL-Server-Management-Studio-21/blob/master/NUMPY_IMPORT_MATHODS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [32]:
#--------------------------------------------  NUMPY – IMPORTANT METHODS -----------------------------------------------
# 1. min() method
# 2. max() method
# 3. sum() method
# 4. reshape() method
# 5. count_nonzero(p) function
# 6. sort() method
# 7. flatten() method
# 8. adding value to array of values
# 9. Diagonal of a Matrix
# 10. Trace of a Matrix
# 11. Adding and Subtracting Matrices

#----------------------------------------------------   MIN() METHOD -------------------------------------------------------
print("###############################################  MIN() METHOD  ######################################################")

import numpy as np
a=[22,33,12,13,24,35,56,67,78,78]
b=np.array(a)
print(b)
print()
print(b.min())

print("--------------------------------------------------------------------------------------------------------------------")

import numpy as np
a=([[22,33,12],[13,24,35],[56,67,78]])
b=np.array(a)
print(b)
print()
print(b.min())

#------------------------------------------------------- MAX() METHOD--------------------------------------------------------
print("################################################  max() method ##########################################################")

import numpy as np
a=([12,1,23,45,67,44,4,444,55,67,89,8,65])
b=np.array(a)
print(b)
print()
print(b.max())

print("------------------------------------------------------------------------------------------------------------------------")

import numpy as np
a=([[1,2,3,4,5],[4,5,6,7,8],[2,3,4,5,6]])
b=np.array(a)
print(b)
print()
print(b.max())

#---------------------------------------------------------- SUM() METHOD ----------------------------------------------
print("###################################################  SUM() METHOD  #############################################")
import numpy as np
a=([[1,2,3,44,5,6,74,5,6,7]])
b=np.array(a)
print(b)
print()
print(b.sum())

print("------------------------------------------------------------------------------------------------------------------")
a=([[1,2,3,4],[4,5,6,7],[4,5,6,7]])
b=np.array(a)
print(b)
print()
print(b.sum())

print("------------------------------------------------------------------------------------------------------------------")
import numpy as np
a=([[1,2,3,4],[4,5,6,7],[4,5,6,7],[1,2,34,4],[67,89,89,90]])
b=np.array(a)
print(b)
print()
print(b.sum())

#------------------------------------------------------- reshape ----------------------------------------------------------
print("################################################  RESHAPE ##########################################################")
import numpy as np
a=([[1,2,3,4],[4,5,6,7],[4,5,6,7],[1,2,34,4],[67,89,89,90]])
b=np.array(a)
print(b)
print()
print(b.reshape(4,5))

print("------------------------------------------------------------------------------------------------------------------")
import numpy as np
a=([[1,2,3,44,5,6,7],[4,5,6,71,2,34,67]])
b=np.array(a)
print(b)
print()
print(b.reshape(7,2))

#------------------------------------------------------- count_nonzero(p) function ---------------------------------------
print("##############################################  COUNT NONZERO(P) #################################################")
import numpy as np
a=([1,2,3,4,0,8,0,9,5])
b=np.array(a)
print(b)
print()
print("the no of non zeros is:",np.count_nonzero(b))

print("------------------------------------------------------------------------------------------------------------------")

import numpy as np
a=([1,2,3],[4,0,8],[0,9,5],[6,8,0])
b=np.array(a)
print(b)
print()
print("the no of non zeros is:",np.count_nonzero(b))

print("------------------------------------------------------------------------------------------------------------------")

import numpy as np
a=([1,0,34,0,8],[0,9,0,8,0])
b=np.array(a)
print(b)
print()
print("the no of non zeros is:",np.count_nonzero(b))

#---------------------------------------------------- sort() method ------------------------------------------------------
print("############################################# SORT() METHOD  ######################################################")
import numpy as np
a=([1,0,34,0,8],[0,9,0,8,0])
b=np.array(a)
print(b)
print()
print(np.sort(b))

print("------------------------------------------------------------------------------------------------------------------")

import numpy as np
a=([1,0,34,0,8],[0,9,0,8,0],[8,6,3,4,5],[3,1,5,6,7])
b=np.array(a)
print(b)
print()
print(np.sort(b))

print("------------------------------------------------------------------------------------------------------------------")

import numpy as np
a=([1,0,34],[55,9,1],[8,6,5],[3,6,7])
b=np.array(a)
print(b)
print()
print(np.sort(b))

#------------------------------------------------------ FLATTEN ------------------------------------------------------------
print("###############################################  FLATTEN   #########################################################")

import numpy as np
a=np.array([[2,1,3,4],[5,4,2,7]])
b=np.array(a)
print(b)
print()
print(b.flatten())



print("----------------------------------------------------------------------------------------------------------------------")

import numpy as np
a=([2,1,3,4],[5,4,2,7],[4,5,6,7])
b=np.array(a)
print(b)
print()
print(b.flatten())

print("-------------------------------------------------------------------------------------------------------------------------")

import numpy as np
a=([23,13],[33,43],[53,42],[22,73])
b=np.array(a)
print(b)
print()
print(b.flatten())

#------------------------------------------------  Diagonal of a Matrix -------------------------------------------------
print("########################################### DIAGONAL OF A MATRIX #################################################")

import numpy as np
a=([[4,3,2],[5,6,7],[8,7,5]])
b=np.array(a)
print(b)
print()
print(np.diagonal(b))

print("------------------------------------------------------------------------------------------------------------")

import numpy as np
a=([[1,4,3,2],[5,2,6,7],[8,7,3,5],[3,2,5,4]])
b=np.array(a)
print(b)
print()
print(np.diagonal(b))

print("------------------------------------------------------------------------------------------------------------")

import numpy as np
a=([[1,4],[5,2]])
b=np.array(a)
print(b)
print()
print(np.diagonal(b))

#------------------------------------------------- adding value to array of values ----------------------------------
print("##########################################  ADDING VALUE TO ARRAY OF VALUE ###################################")

import numpy as np
a=([[1,4],[5,2]])
b=np.array(a)
print(b)
print()
print(b+2)

print("-------------------------------------------------------------------------------------------------------------")
import numpy as np
a=([[1,4],[5,2]])
b=np.array(a)
print(b)
print()
print(b+3)

print("-------------------------------------------------------------------------------------------------------------")
import numpy as np
a=([[1,4],[5,2]])
b=np.array(a)
print(b)
print()
print(b+5)

#------------------------------------------------------ TRACE MATRIX  ------------------------------------------------
print("################################################ TRACE MATRIX #################################################")

import numpy as np
a=([[4,10,2],[5,60,7],[8,70,5]])
b=np.array(a)
print(b)
print()
print(b.trace())

print("----------------------------------------------------------------------------------------------------------------")

import numpy as np
a=([[4,100,2],[5,160,7],[8,70,5]])
b=np.array(a)
print(b)
print()
print(b.trace())

print("----------------------------------------------------------------------------------------------------------------")

import numpy as np
a=([[4,50,2],[5,50,7],[8,70,5]])
b=np.array(a)
print(b)
print()
print(b.trace())


###############################################  MIN() METHOD  ######################################################
[22 33 12 13 24 35 56 67 78 78]

12
--------------------------------------------------------------------------------------------------------------------
[[22 33 12]
 [13 24 35]
 [56 67 78]]

12
################################################  max() method ##########################################################
[ 12   1  23  45  67  44   4 444  55  67  89   8  65]

444
------------------------------------------------------------------------------------------------------------------------
[[1 2 3 4 5]
 [4 5 6 7 8]
 [2 3 4 5 6]]

8
###################################################  SUM() METHOD  #############################################
[[ 1  2  3 44  5  6 74  5  6  7]]

153
------------------------------------------------------------------------------------------------------------------
[[1 2 3 4]
 [4 5 6 7]
 [4 5 6 7]]

54
--------------------------------------