<a href="https://colab.research.google.com/github/mohanraju2002/SQL-Server-Management-Studio-21/blob/master/numpyfundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [25]:
#  NUMPY  FUNDAMENTALS

# 1. numpy.ndim
# 2. Indexing
# 3. Slicing
# 4. Creating a array with all zeros 0
# 5. Creating a array with all ones

#------------------------------- 1.NUMPY.NDIM--------------------------------------------

print("##########################  NUMPY .NDIM  #########################################")


import numpy as np
a=18
b=np.array(a)                   # 0 DIMENSIONAL
print(b)
print(type(b))
print(b.ndim)

print("---------------------------------------------------------------------------------------")

import numpy as np
a=[10,20,30,40,50]
b=np.array(a)
print(b)                         # 1 DIMENSIONAL
print(type(b))
print(b.ndim)

print("---------------------------------------------------------------------------------------")

import numpy as np
a=([[10,20,30],[40,50,60]])
b=np.array(a)                    # 2 DIMENSIONAL
print(b)
print(type(b))
print(b.ndim)


#-------------------------------------- 2.INDEXING-----------------------------------------------
print("################################ INDEXING ################################################")

# INDEX IS STARTIG WITH 0

import numpy as np
a=[10,20,32,43,45,33]
b=np.array(a)
print(b)
print(b[0])                  # IN 1 DIMENSIONAL
print(b[1])
print(b[2])

print("---------------------------------------------------------------------------------------")

import numpy as np
a=([[10,20,32],[43,45,33]])
b=np.array(a)
print(b)
print(b[0,1])               # IN 2 DIMENSIONAL
print(b[0,2])
print(b[1,1])
print(b[1,0])

print("---------------------------------------------------------------------------------------")

import numpy as np
a=([[10,20,32],[43,45,33],[44,22,11],[22,33,77]])
b=np.array(a)
print(b)
print(b[0,1])
print(b[0,2])
print(b[2,1])                 # IN 2 DIMENSIONAL
print(b[3,0])
print(b[3,2])

print("---------------------------------------------------------------------------------------")

#------------------------------------------ 3.SLICING ------------------------------------------
print("#####################################  SLICING  ########################################")

import numpy as np
a=[10,20,32,43,45,33]
b=np.array(a)
print(b)                      # INDEX IS STARTIG WITH 0
print(b[2:])
print(b[0:3])
print(b[1:5])

#-----------------------------------  4. Creating a array with all zeros 0  ---------------------
print("#####################################  ZEROS  ########################################")

import numpy as np
a=np.zeros(5)
print(a)

print("---------------------------------------------------------------------------------------")
import numpy as np
a=np.zeros(6)
print(a)

print("---------------------------------------------------------------------------------------")

import numpy as np
a=np.zeros((3,7))
print(a)


#-----------------------------------  4. Creating a array with all ONES 1  ---------------------
print("#####################################  ONES  ########################################")

import numpy as np
a=np.ones(5)
print(a)

print("---------------------------------------------------------------------------------------")
import numpy as np
a=np.ones(6)
print(a)

print("---------------------------------------------------------------------------------------")

import numpy as np
a=np.ones((3,7))
print(a)










##########################  NUMPY .NDIM  #########################################
18
<class 'numpy.ndarray'>
0
---------------------------------------------------------------------------------------
[10 20 30 40 50]
<class 'numpy.ndarray'>
1
---------------------------------------------------------------------------------------
[[10 20 30]
 [40 50 60]]
<class 'numpy.ndarray'>
2
################################ INDEXING ################################################
[10 20 32 43 45 33]
10
20
32
---------------------------------------------------------------------------------------
[[10 20 32]
 [43 45 33]]
20
32
45
43
---------------------------------------------------------------------------------------
[[10 20 32]
 [43 45 33]
 [44 22 11]
 [22 33 77]]
20
32
22
22
77
---------------------------------------------------------------------------------------
#####################################  SLICING  ########################################
[10 20 32 43 45 33]
[32 43 45 33]
[10 20 32]