<a href="https://colab.research.google.com/github/mohanraju2002/SQL-NUMPY/blob/master/NUMPY_Projects.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
A=np.array([[2,4,6,8],
    [5,6,7,8],
    [4,7,9,8]])

B=np.array([[2,3,4,5],
    [1,2,2,2],
    [7,8,9,7]])

import numpy as np
A=np.array([[2,4,6,8],
    [5,6,7,8],
    [4,7,9,8]])

B=np.array([[2,3,4,5],
    [1,2,2,2],
    [7,8,9,7]])

print("the A matrix is:\n",A)
print()
print("the B matrix is:\n",B)
print()
print(""" 1=ADDITION
          2=SUBSTRACTION
          3=MULTIPLICATION
          4=A.TRANSPOSE
          5=B.TRANSPOSE
          6=(A,B.T)
          7=(B,A.T) """
        )

if A.shape==B.shape:

  choice=int(input("ENTER YOUR CHOICE:"))
  if choice==1:
    print("THE SUM OF TWO MATRIX IS:\n",A+B)
  elif choice==2:
    print("THE SUBSTRACTION OF TWO MATRIX IS:\n",A-B)
  elif choice==3:
    print("THE MULTIPLICATION OF TWO MATRIXS IS:\n",A*B)
  elif choice==4:
    print("The transpose of A is:\n",np.transpose(A))
  elif choice==5:
    C = np.dot(A, B.T)
    print("THE MATRIX MULTIPLICATION OF A AND B.T IS:\n", C)
  elif choice==6:
    print("The transpose of B is:\n",np.transpose(B))
  elif choice==7:
    D=np.dot(B,A.T)
    print("THE MATRIX MULTIPLICATION OF B AND A.T IS:\n", D)
  else:
    print("OUT OF RANGE")
else:
  print("BOTH ARE NOT SAME")

the A matrix is:
 [[2 4 6 8]
 [5 6 7 8]
 [4 7 9 8]]

the B matrix is:
 [[2 3 4 5]
 [1 2 2 2]
 [7 8 9 7]]

 1=ADDITION
          2=SUBSTRACTION
          3=MULTIPLICATION
          4=A.TRANSPOSE
          5=B.TRANSPOSE
          6=(A,B.T)
          7=(B,A.T) 
ENTER YOUR CHOICE:2
THE SUBSTRACTION OF TWO MATRIX IS:
 [[ 0  1  2  3]
 [ 4  4  5  6]
 [-3 -1  0  1]]


In [ ]:
import numpy as np
school=([99,86,95],
        [89,76,96],
        [89,87,82],
        [56,67,59],
        [45,36,38]
        )

data=np.array(school)
print(data)
print()
a=("1=mohan","2=dimple","3=murari","4=ganesh","5=lokesh","6=avg marks of 5 students","7=topper of each subject")
for i in a:
  print(i)
choice=input("WHAT DO you WANT:")
if choice=="1":
  marks=data[0]
  print("TELUGU=",data[0,0],"\nHINDI =",data[0,1],"\nENGLISH=",data[0,2])
  print("THE TOTAL MARKS IN 3 SUBJECTS=",marks.sum())
  print("THE AVERAGE MARKS IN 3 SUBJECTS=",round(marks.mean(),2))
  print("THE MAXIMUM MARKS IN 3 SUBJECTS=",marks.max())
  print("THE MINIMUM MARKS IN 3 SUBJECTS=",marks.min())
  print("THE STD DEVIATION IN 3 SUBJECTS=",marks.std())
elif choice=="2":
  marks=data[1]
  print("TELUGU=",data[1,0],"\nHINDI =",data[1,1],"\nENGLISH=",data[1,2])
  print("THE TOTAL MARKS IN 3 SUBJECTS=",marks.sum())
  print("THE AVERAGE MARKS IN 3 SUBJECTS",round(marks.mean(),2))
  print("THE MAXIMUM MARKS IN 3 SUBJECTS=",marks.max())
  print("THE MINIMUM MARKS IN 3 SUBJECTS=",marks.min())
  print("THE STD DEVIATION IN 3 SUBJECTS=",marks.std())
elif choice=="3":
  marks=data[2]
  print("TELUGU=",data[2,0],"\nHINDI =",data[2,1],"\nENGLISH=",data[2,2])
  print("THE TOTAL MARKS IN 3 SUBJECTS=",marks.sum())
  print("THE AVERAGE MARKS IN 3 SUBJECTS",round(marks.mean(),2))
  print("THE MAXIMUM MARKS IN 3 SUBJECTS=",marks.max())
  print("THE MINIMUM MARKS IN 3 SUBJECTS=",marks.min())
  print("THE STD DEVIATION IN 3 SUBJECTS=",marks.std())
elif choice=="4":
  marks=data[3]
  print("TELUGU=",data[3,0],"\nHINDI =",data[3,1],"\nENGLISH=",data[3,2])
  print("THE TOTAL MARKS IN 3 SUBJECTS=",marks.sum())
  print("THE AVERAGE MARKS IN 3 SUBJECTS",round(marks.mean(),2))
  print("THE MAXIMUM MARKS IN 3 SUBJECTS=",marks.max())
  print("THE MINIMUM MARKS IN 3 SUBJECTS=",marks.min())
  print("THE STD DEVIATION IN 3 SUBJECTS=",marks.std())
elif choice=="5":
  marks=data[4]
  print("TELUGU=",data[4,0],"\nHINDI =",data[4,1],"\nENGLISH=",data[4,2])
  print("THE TOTAL MARKS IN 3 SUBJECTS=",marks.sum())
  print("THE AVERAGE MARKS IN 3 SUBJECTS",round(marks.mean(),2))
  print("THE MAXIMUM MARKS IN 3 SUBJECTS=",marks.max())
  print("THE MINIMUM MARKS IN 3 SUBJECTS=",marks.min())
  print("THE STD DEVIATION IN 3 SUBJECTS=",marks.std())
elif choice=="6":
  mohan=data[0]
  dimple=data[1]
  murari=data[2]
  ganesh=data[3]
  lokesh=data[4]
  print("THE AVERAGE MARKS OF MOHAN =",round(mohan.mean(),2))
  print("THE AVERAGE MARKS OF DIMPLE =",round(dimple.mean(),2))
  print("THE AVERAGE MARKS OF MURARI =",round(murari.mean(),2))
  print("THE AVERAGE MARKS OF GANESH =",round(ganesh.mean(),2))
  print("THE AVERAGE MARKS OF LOKESH =",round(lokesh.mean(),2))
elif choice=="7":
  names = ["Mohan", "Dimple", "Murari", "Ganesh", "Lokesh"]

  subjects = ["Telugu", "Hindi", "English"]
  print()
  print("Marks Table:\n", data)
  print()
  for i in range(3):
      subject_marks = data[:, i]
      topper_index = subject_marks.argmax()
      topper_name = names[topper_index]
      topper_marks = subject_marks[topper_index]

      print("Topper in", subjects[i], "=", topper_name, "with", topper_marks, "marks")

else:
    print("the student is not my class")


[[99 86 95]
 [89 76 96]
 [89 87 82]
 [56 67 59]
 [45 36 38]]

1=mohan
2=dimple
3=murari
4=ganesh
5=lokesh
6=avg marks of 5 students
7=topper of each subject
WHAT DO you WANT:4
TELUGU= 56 
HINDI = 67 
ENGLISH= 59
THE TOTAL MARKS IN 3 SUBJECTS= 182
THE AVERAGE MARKS IN 3 SUBJECTS 60.67
THE MAXIMUM MARKS IN 3 SUBJECTS= 67
THE MINIMUM MARKS IN 3 SUBJECTS= 56
THE STD DEVIATION IN 3 SUBJECTS= 4.642796092394707


In [ ]:
import numpy as np

rolls = np.random.randint(1, 7, 1000)

for i in range(1, 7):
    count = np.count_nonzero(rolls == i)
    print("Number", i, "dies in", count, "times")
    print("Probability =", count / 1000)
    print()

Number 1 dies in 180 times
Probability = 0.18

Number 2 dies in 174 times
Probability = 0.174

Number 3 dies in 146 times
Probability = 0.146

Number 4 dies in 166 times
Probability = 0.166

Number 5 dies in 149 times
Probability = 0.149

Number 6 dies in 185 times
Probability = 0.185



In [ ]:



import numpy as np
count=0
week = [34, 25, 35, 36, 37, 70, 10]
days = ["MONDAY", "TUESDAY", "WEDNESDAY", "THURSDAY", "FRIDAY", "SATURDAY" ,"SUNDAY"]
temp = np.array(week)
print(temp)
print()
print("HIGHEST TEMPERATURE IN THIS WEEK IS =", temp.max())
print()
print("LOWEST TEMPERATURE IN THIS WEEK IS =", temp.min())
print()
print("AVERAGE TEMPERATURE IN THIS WEEK IS =", temp.mean())
print()
high = temp.argmax()
print("THE HOTTEST DAY IN THIS WEEK IS =", days[high])
print()
low=temp.argmin()
print("THE LOWEST DAY IN THIS WEEK IS =", days[low])
print()
above=0
below=0
for i in temp:
  if i>35.285714285714285:
    above=above+1
  else:
    below=below+1
print("ABOVE THE AVERAGE TEMPERATURE DAYS=",above)
print()
print("BELOW THE AVERAGE TEMPERATURE DAYS=",below)


[34 25 35 36 37 70 10]

HIGHEST TEMPERATURE IN THIS WEEK IS = 70

LOWEST TEMPERATURE IN THIS WEEK IS = 10

AVERAGE TEMPERATURE IN THIS WEEK IS = 35.285714285714285

THE HOTTEST DAY IN THIS WEEK IS = SATURDAY

THE LOWEST DAY IN THIS WEEK IS = SUNDAY

ABOVE THE AVERAGE TEMPERATURE DAYS= 3

BELOW THE AVERAGE TEMPERATURE DAYS= 4
